### ISSUE TITLE
Long stack when a task fails in v2.3+

### ISSUE THREAD

**Issue by mcafaro** [matlab-actions/run-build#46]
There is a long stack when a task fails in v2.3+ (i.e. since the introduction of `BuildSummaryPlugin` and `GitHubLogPlugin`).

For example, the following build file:

```matlab
function plan = buildfile
plan = buildplan(localfunctions);
plan.DefaultTasks = "package";
end

function packageTask(~)
error('fail!')
end
```

produces the following stack:

<img width="1503" alt="Screenshot 2024-07-15 at 3 57 01 PM" src="https://github.com/user-attachments/assets/153508e4-280c-44fe-89aa-ece92cebdcbc">

This is likely because the build framework is only trimming the stack up to the first framework folder frame and the ciplugins folder is not in the framework folder.

**Comment by nbhoski** [comment]
may i know what do you mean by ciplugins folder is not in the framework folder. ?

**Comment by mcafaro** [comment]
The build tool will trim all frames at the end of an exception that come from files in <matlabroot>/core/+matlab/+buildtool assuming most people are not interested in seeing all the frames from the framework itself. Because there is now a +ciplugins frame deep in the stack, the build tool is only trimming up to that exception, resulting in a very long stack trace for a simple error.

This is an issue that needs to be fixed in the build tool framework code but it was not a problem until v2.3 introduced +ciplugins.

**Comment by nbhoski** [comment]
I see, Thanks mark. will look into buildtool to fix it. i can take it parallelly. Do you think this is blocker for v2.4 release ? if not I can release current version and fix it in build tool simultaneously

**Comment by mcafaro** [comment]
We will fix this in the build tool framework when stack frame hiding is available. I have created an issue to track that on the build tool codebase. Closing the issue here because there is nothing `run-build` can do to solve this issue.
