### ISSUE TITLE
Getting security alerts while using this action for enterprise project

### ISSUE THREAD

**Issue by manoj27730** [matlab-actions/run-build#7]
Hi Team,

I need this actions to be used by my project and since it's not allowed by default our enterprise GitHub Team need to review and add it for our project. Our GitHub Team has found alert and mentioned below point.

**"The actions requested are available on our github instance but we are seeing dependabot alerts. Since those repo have vulnerabilities, we won’t be able to make it public. Look like it’s patched on the master but they haven’t release it. Please file issue with the actions owner to release patched version. After that, we can make it available for your team to use."**

Can you please look into it and help.

**Comment by manoj27730** [comment]
<img width="532" alt="Alert" src="https://user-images.githubusercontent.com/24359931/199657922-043bf5cf-92d8-4829-b974-cd86f833ac2a.PNG">

**Comment by davidbuzinski** [comment]
Hi @manoj27730 I bumped the npm dependencies for the other MATLAB actions. I am not seeing the same vulnerabilities present in this action. It looks like the attached screenshot is for run-command. Are you able to confirm that your organization is using this action, and if so, can you let us know which dependencies you are seeing in your alerts?

Thanks,
David

**Comment by manoj27730** [comment]
Hi David,

   Our Enterprise GitHub Team has confirmed it doesn't have any vulnerabilities. Please close this request.

Thanks,
Manoj
